name: WakaTime status update

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: "00 09 * * *"

jobs:
  github-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: vn7n24fzkq/github-profile-summary-cards@release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #  with:
      #    USERNAME: ${{ github.repository_owner }}
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: True
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: True
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
